GradientBoosting:
  class: revscoring.scoring.models.GradientBoosting
  params:
    n_estimators: [500, 700, 1200, 1500, 2000]
    max_depth: [5, 7, 9, 11]
    max_features: ["log2"]
    learning_rate: [0.001, 0.01, 0.1,  0.5]
