RandomForest:
  class: revscoring.scoring.models.RandomForest
  params:
    n_estimators: [128, 256, 512, 1024]
    min_samples_leaf: [1, 3, 5, 7, 13]
    max_features: ["log2"]
    criterion: ["gini", "entropy"]
